var searchData=
[
  ['decryptdata',['DecryptData',['../interface_m_a_s_foundation_1_1_n_s_data___m_a_s.html#af8bbd1a8f8e9e8bc93421cbced620b8d',1,'MASFoundation::NSData_MAS']]],
  ['deleteforkey',['DeleteForKey',['../interface_m_a_s_foundation_1_1_m_a_s_shared_storage.html#ab8c2dfca87928ca4bf440b98c1b5a117',1,'MASFoundation::MASSharedStorage']]],
  ['deletefrom',['DeleteFrom',['../interface_m_a_s_foundation_1_1_m_a_s_request.html#ad646e40ba1f4a88e819d44e0d1cb9e39',1,'MASFoundation.MASRequest.DeleteFrom()'],['../interface_m_a_s_foundation_1_1_m_a_s.html#a5dbc4a389d08e8cac480dbcf8a5574a7',1,'MASFoundation.MAS.DeleteFrom(string endPointPath, [NullAllowed] NSDictionary parameterInfo, [NullAllowed] NSDictionary headerInfo, [NullAllowed] MASResponseInfoErrorBlock completion)'],['../interface_m_a_s_foundation_1_1_m_a_s.html#a5ad03c1cf3d2cff1942587a0efd19e35',1,'MASFoundation.MAS.DeleteFrom(string endPointPath, [NullAllowed] NSDictionary parameterInfo, [NullAllowed] NSDictionary headerInfo, MASRequestResponseType requestType, MASRequestResponseType responseType, [NullAllowed] MASResponseInfoErrorBlock completion)'],['../interface_m_a_s_foundation_1_1_m_a_s.html#afb7eddaf7afd05d9f0e38a43ec59b63e',1,'MASFoundation.MAS.DeleteFrom(string endPointPath, [NullAllowed] NSDictionary parameterInfo, [NullAllowed] NSDictionary headerInfo, MASRequestResponseType requestType, MASRequestResponseType responseType, bool isPublic, [NullAllowed] MASResponseInfoErrorBlock completion)']]],
  ['deregisterwithcompletion',['DeregisterWithCompletion',['../interface_m_a_s_foundation_1_1_m_a_s_device.html#a3ce1746c4743a45b3ae4d68bba781a3b',1,'MASFoundation::MASDevice']]],
  ['detectserverchangewithcurrentconfiguration',['DetectServerChangeWithCurrentConfiguration',['../interface_m_a_s_foundation_1_1_m_a_s_configuration.html#a2ae6bfead84be3599e0a9bf65fecbfff',1,'MASFoundation::MASConfiguration']]],
  ['didreceiveauthorizationcode',['DidReceiveAuthorizationCode',['../interface_m_a_s_foundation_1_1_m_a_s_proximity_login_delegate.html#a93c0de57a3608d0c8993fc2cfe0fc498',1,'MASFoundation.MASProximityLoginDelegate.DidReceiveAuthorizationCode()'],['../interface_m_a_s_foundation_1_1_m_a_s_authorization_response_delegate.html#ad5383670c67ca26a830b0f0ed5f129ae',1,'MASFoundation.MASAuthorizationResponseDelegate.DidReceiveAuthorizationCode()'],['../interface_m_a_s_foundation_1_1_m_a_s_social_login_delegate.html#a434077d7555c08e394760c5e7bfec9da',1,'MASFoundation.MASSocialLoginDelegate.DidReceiveAuthorizationCode()']]],
  ['didreceivebleproximityloginstateupdate',['DidReceiveBLEProximityLoginStateUpdate',['../interface_m_a_s_foundation_1_1_m_a_s_proximity_login_delegate.html#acb228106648a05e6715d66b171dca73c',1,'MASFoundation::MASProximityLoginDelegate']]],
  ['didreceiveerror',['DidReceiveError',['../interface_m_a_s_foundation_1_1_m_a_s_authorization_response_delegate.html#adcc9eed1d7fdcc6a573c5bac586b8948',1,'MASFoundation.MASAuthorizationResponseDelegate.DidReceiveError()'],['../interface_m_a_s_foundation_1_1_m_a_s_social_login_delegate.html#a41a3f6c99d02cd70cd039f70a9b95a2d',1,'MASFoundation.MASSocialLoginDelegate.DidReceiveError()']]],
  ['didreceiveproximityloginerror',['DidReceiveProximityLoginError',['../interface_m_a_s_foundation_1_1_m_a_s_proximity_login_delegate.html#a2b72630e0ddf949d9e04daf601fb171d',1,'MASFoundation::MASProximityLoginDelegate']]],
  ['didstartloadingwebview',['DidStartLoadingWebView',['../interface_m_a_s_foundation_1_1_m_a_s_social_login_delegate.html#a3be9f8e491e01830a595108779fe9741',1,'MASFoundation::MASSocialLoginDelegate']]],
  ['didstoploadingwebview',['DidStopLoadingWebView',['../interface_m_a_s_foundation_1_1_m_a_s_social_login_delegate.html#ad5a61168454b835f6279898041e13f22',1,'MASFoundation::MASSocialLoginDelegate']]],
  ['disconnectwithcompletionhandler',['DisconnectWithCompletionHandler',['../interface_m_a_s_foundation_1_1_m_a_s_m_q_t_t_client.html#ae366d519511ef97b3d7a2171edc0abe9',1,'MASFoundation::MASMQTTClient']]]
];
