#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BasicAuthSample.Resource", IsApplication=true)]

namespace BasicAuthSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int scim_operators = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BackgroundImage = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ca_logo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080008
			public const int deregister = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int invokeApi = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int lockSession = 2131230726;
			
			// aapt resource value: 0x7f080003
			public const int login = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int logout = 2131230725;
			
			// aapt resource value: 0x7f080000
			public const int setClientCredentialsFlow = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int setPasswordFlow = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int startSDK = 2131230722;
			
			// aapt resource value: 0x7f080007
			public const int unlockSession = 2131230727;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int ormlite_config = 2131034112;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int acc_name = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int attempting_to_connect = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int client_already_connected = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int client_already_disconnected = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int connect_error = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int connected = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int connection_attempt = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int connection_lost = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int could_not_connect = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int could_not_disconnect = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int could_not_publish = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int could_not_subscribe = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int could_not_unsubscribe = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int delivery_failed = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int delivery_succeeded = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int disconnected = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int login_not_connected_error = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int published = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int resources = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int subscribe_success = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int subscribed = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int unsubscribed = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int uri_create_failed = 2131165207;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int massharedauthenticator = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int mastest = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int prefs = 2130968578;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
